//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PAARv2Model", "FK_sid_FreightRates_sid_FreightRates", "sid_VehicleCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PAARS.DAL.sid_VehicleCategory), "sid_FreightRates", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PAARS.DAL.sid_FreightRates), true)]
[assembly: EdmRelationshipAttribute("PAARv2Model", "FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PAARS.DAL.sid_VehicleCategory), "sid_VehicleTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PAARS.DAL.sid_VehicleTypes), true)]

#endregion

namespace PAARS.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PAARv2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PAARv2Entities object using the connection string found in the 'PAARv2Entities' section of the application configuration file.
        /// </summary>
        public PAARv2Entities() : base("name=PAARv2Entities", "PAARv2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PAARv2Entities object.
        /// </summary>
        public PAARv2Entities(string connectionString) : base(connectionString, "PAARv2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PAARv2Entities object.
        /// </summary>
        public PAARv2Entities(EntityConnection connection) : base(connection, "PAARv2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExchangeRate> ExchangeRate
        {
            get
            {
                if ((_ExchangeRate == null))
                {
                    _ExchangeRate = base.CreateObjectSet<ExchangeRate>("ExchangeRate");
                }
                return _ExchangeRate;
            }
        }
        private ObjectSet<ExchangeRate> _ExchangeRate;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExchangeRateView> ExchangeRateView
        {
            get
            {
                if ((_ExchangeRateView == null))
                {
                    _ExchangeRateView = base.CreateObjectSet<ExchangeRateView>("ExchangeRateView");
                }
                return _ExchangeRateView;
            }
        }
        private ObjectSet<ExchangeRateView> _ExchangeRateView;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ValuationTPD> ValuationTPD
        {
            get
            {
                if ((_ValuationTPD == null))
                {
                    _ValuationTPD = base.CreateObjectSet<ValuationTPD>("ValuationTPD");
                }
                return _ValuationTPD;
            }
        }
        private ObjectSet<ValuationTPD> _ValuationTPD;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sid_FreightRates> sid_FreightRates
        {
            get
            {
                if ((_sid_FreightRates == null))
                {
                    _sid_FreightRates = base.CreateObjectSet<sid_FreightRates>("sid_FreightRates");
                }
                return _sid_FreightRates;
            }
        }
        private ObjectSet<sid_FreightRates> _sid_FreightRates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sid_VehicleCategory> sid_VehicleCategory
        {
            get
            {
                if ((_sid_VehicleCategory == null))
                {
                    _sid_VehicleCategory = base.CreateObjectSet<sid_VehicleCategory>("sid_VehicleCategory");
                }
                return _sid_VehicleCategory;
            }
        }
        private ObjectSet<sid_VehicleCategory> _sid_VehicleCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sid_VehicleTypes> sid_VehicleTypes
        {
            get
            {
                if ((_sid_VehicleTypes == null))
                {
                    _sid_VehicleTypes = base.CreateObjectSet<sid_VehicleTypes>("sid_VehicleTypes");
                }
                return _sid_VehicleTypes;
            }
        }
        private ObjectSet<sid_VehicleTypes> _sid_VehicleTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HSCodeTariff> HSCodeTariff
        {
            get
            {
                if ((_HSCodeTariff == null))
                {
                    _HSCodeTariff = base.CreateObjectSet<HSCodeTariff>("HSCodeTariff");
                }
                return _HSCodeTariff;
            }
        }
        private ObjectSet<HSCodeTariff> _HSCodeTariff;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TariffBenchmark> TariffBenchmark
        {
            get
            {
                if ((_TariffBenchmark == null))
                {
                    _TariffBenchmark = base.CreateObjectSet<TariffBenchmark>("TariffBenchmark");
                }
                return _TariffBenchmark;
            }
        }
        private ObjectSet<TariffBenchmark> _TariffBenchmark;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExchangeRate EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExchangeRate(ExchangeRate exchangeRate)
        {
            base.AddObject("ExchangeRate", exchangeRate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExchangeRateView EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExchangeRateView(ExchangeRateView exchangeRateView)
        {
            base.AddObject("ExchangeRateView", exchangeRateView);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ValuationTPD EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToValuationTPD(ValuationTPD valuationTPD)
        {
            base.AddObject("ValuationTPD", valuationTPD);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sid_FreightRates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosid_FreightRates(sid_FreightRates sid_FreightRates)
        {
            base.AddObject("sid_FreightRates", sid_FreightRates);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sid_VehicleCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosid_VehicleCategory(sid_VehicleCategory sid_VehicleCategory)
        {
            base.AddObject("sid_VehicleCategory", sid_VehicleCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sid_VehicleTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosid_VehicleTypes(sid_VehicleTypes sid_VehicleTypes)
        {
            base.AddObject("sid_VehicleTypes", sid_VehicleTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HSCodeTariff EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHSCodeTariff(HSCodeTariff hSCodeTariff)
        {
            base.AddObject("HSCodeTariff", hSCodeTariff);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TariffBenchmark EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTariffBenchmark(TariffBenchmark tariffBenchmark)
        {
            base.AddObject("TariffBenchmark", tariffBenchmark);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="ExchangeRate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExchangeRate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExchangeRate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="week">Initial value of the Week property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static ExchangeRate CreateExchangeRate(global::System.Int32 id, global::System.DateTime week, global::System.Decimal rate)
        {
            ExchangeRate exchangeRate = new ExchangeRate();
            exchangeRate.Id = id;
            exchangeRate.Week = week;
            exchangeRate.Rate = rate;
            return exchangeRate;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Week
        {
            get
            {
                return _Week;
            }
            set
            {
                OnWeekChanging(value);
                ReportPropertyChanging("Week");
                _Week = StructuralObject.SetValidValue(value, "Week");
                ReportPropertyChanged("Week");
                OnWeekChanged();
            }
        }
        private global::System.DateTime _Week;
        partial void OnWeekChanging(global::System.DateTime value);
        partial void OnWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrencyCode
        {
            get
            {
                return _CurrencyCode;
            }
            set
            {
                OnCurrencyCodeChanging(value);
                ReportPropertyChanging("CurrencyCode");
                _CurrencyCode = StructuralObject.SetValidValue(value, true, "CurrencyCode");
                ReportPropertyChanged("CurrencyCode");
                OnCurrencyCodeChanged();
            }
        }
        private global::System.String _CurrencyCode;
        partial void OnCurrencyCodeChanging(global::System.String value);
        partial void OnCurrencyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value, "Rate");
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Decimal _Rate;
        partial void OnRateChanging(global::System.Decimal value);
        partial void OnRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value, "ModifiedDate");
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true, "ModifiedBy");
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="ExchangeRateView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExchangeRateView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExchangeRateView object.
        /// </summary>
        /// <param name="currencyCode">Initial value of the CurrencyCode property.</param>
        /// <param name="week">Initial value of the Week property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static ExchangeRateView CreateExchangeRateView(global::System.String currencyCode, global::System.DateTime week, global::System.Decimal rate)
        {
            ExchangeRateView exchangeRateView = new ExchangeRateView();
            exchangeRateView.CurrencyCode = currencyCode;
            exchangeRateView.Week = week;
            exchangeRateView.Rate = rate;
            return exchangeRateView;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CurrencyCode
        {
            get
            {
                return _CurrencyCode;
            }
            set
            {
                if (_CurrencyCode != value)
                {
                    OnCurrencyCodeChanging(value);
                    ReportPropertyChanging("CurrencyCode");
                    _CurrencyCode = StructuralObject.SetValidValue(value, false, "CurrencyCode");
                    ReportPropertyChanged("CurrencyCode");
                    OnCurrencyCodeChanged();
                }
            }
        }
        private global::System.String _CurrencyCode;
        partial void OnCurrencyCodeChanging(global::System.String value);
        partial void OnCurrencyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrencyName
        {
            get
            {
                return _CurrencyName;
            }
            set
            {
                OnCurrencyNameChanging(value);
                ReportPropertyChanging("CurrencyName");
                _CurrencyName = StructuralObject.SetValidValue(value, true, "CurrencyName");
                ReportPropertyChanged("CurrencyName");
                OnCurrencyNameChanged();
            }
        }
        private global::System.String _CurrencyName;
        partial void OnCurrencyNameChanging(global::System.String value);
        partial void OnCurrencyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Week
        {
            get
            {
                return _Week;
            }
            set
            {
                if (_Week != value)
                {
                    OnWeekChanging(value);
                    ReportPropertyChanging("Week");
                    _Week = StructuralObject.SetValidValue(value, "Week");
                    ReportPropertyChanged("Week");
                    OnWeekChanged();
                }
            }
        }
        private global::System.DateTime _Week;
        partial void OnWeekChanging(global::System.DateTime value);
        partial void OnWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                if (_Rate != value)
                {
                    OnRateChanging(value);
                    ReportPropertyChanging("Rate");
                    _Rate = StructuralObject.SetValidValue(value, "Rate");
                    ReportPropertyChanged("Rate");
                    OnRateChanged();
                }
            }
        }
        private global::System.Decimal _Rate;
        partial void OnRateChanging(global::System.Decimal value);
        partial void OnRateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="HSCodeTariff")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HSCodeTariff : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HSCodeTariff object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="hSCode">Initial value of the HSCode property.</param>
        /// <param name="casseteLevy">Initial value of the CasseteLevy property.</param>
        /// <param name="environmentalExcise">Initial value of the EnvironmentalExcise property.</param>
        /// <param name="processingFee">Initial value of the ProcessingFee property.</param>
        /// <param name="importLevy">Initial value of the ImportLevy property.</param>
        /// <param name="getFund">Initial value of the GetFund property.</param>
        public static HSCodeTariff CreateHSCodeTariff(global::System.Int32 id, global::System.String hSCode, global::System.Decimal casseteLevy, global::System.Decimal environmentalExcise, global::System.Decimal processingFee, global::System.Decimal importLevy, global::System.Decimal getFund)
        {
            HSCodeTariff hSCodeTariff = new HSCodeTariff();
            hSCodeTariff.Id = id;
            hSCodeTariff.HSCode = hSCode;
            hSCodeTariff.CasseteLevy = casseteLevy;
            hSCodeTariff.EnvironmentalExcise = environmentalExcise;
            hSCodeTariff.ProcessingFee = processingFee;
            hSCodeTariff.ImportLevy = importLevy;
            hSCodeTariff.GetFund = getFund;
            return hSCodeTariff;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HSCode
        {
            get
            {
                return _HSCode;
            }
            set
            {
                OnHSCodeChanging(value);
                ReportPropertyChanging("HSCode");
                _HSCode = StructuralObject.SetValidValue(value, false, "HSCode");
                ReportPropertyChanged("HSCode");
                OnHSCodeChanged();
            }
        }
        private global::System.String _HSCode;
        partial void OnHSCodeChanging(global::System.String value);
        partial void OnHSCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StandardUnitOfQuantity
        {
            get
            {
                return _StandardUnitOfQuantity;
            }
            set
            {
                OnStandardUnitOfQuantityChanging(value);
                ReportPropertyChanging("StandardUnitOfQuantity");
                _StandardUnitOfQuantity = StructuralObject.SetValidValue(value, true, "StandardUnitOfQuantity");
                ReportPropertyChanged("StandardUnitOfQuantity");
                OnStandardUnitOfQuantityChanged();
            }
        }
        private global::System.String _StandardUnitOfQuantity;
        partial void OnStandardUnitOfQuantityChanging(global::System.String value);
        partial void OnStandardUnitOfQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImportDuty
        {
            get
            {
                return _ImportDuty;
            }
            set
            {
                OnImportDutyChanging(value);
                ReportPropertyChanging("ImportDuty");
                _ImportDuty = StructuralObject.SetValidValue(value, true, "ImportDuty");
                ReportPropertyChanged("ImportDuty");
                OnImportDutyChanged();
            }
        }
        private global::System.String _ImportDuty;
        partial void OnImportDutyChanging(global::System.String value);
        partial void OnImportDutyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImportVAT
        {
            get
            {
                return _ImportVAT;
            }
            set
            {
                OnImportVATChanging(value);
                ReportPropertyChanging("ImportVAT");
                _ImportVAT = StructuralObject.SetValidValue(value, true, "ImportVAT");
                ReportPropertyChanged("ImportVAT");
                OnImportVATChanged();
            }
        }
        private global::System.String _ImportVAT;
        partial void OnImportVATChanging(global::System.String value);
        partial void OnImportVATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImportNHIL
        {
            get
            {
                return _ImportNHIL;
            }
            set
            {
                OnImportNHILChanging(value);
                ReportPropertyChanging("ImportNHIL");
                _ImportNHIL = StructuralObject.SetValidValue(value, true, "ImportNHIL");
                ReportPropertyChanged("ImportNHIL");
                OnImportNHILChanged();
            }
        }
        private global::System.String _ImportNHIL;
        partial void OnImportNHILChanging(global::System.String value);
        partial void OnImportNHILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeUnitOfQuantity
        {
            get
            {
                return _TradeUnitOfQuantity;
            }
            set
            {
                OnTradeUnitOfQuantityChanging(value);
                ReportPropertyChanging("TradeUnitOfQuantity");
                _TradeUnitOfQuantity = StructuralObject.SetValidValue(value, true, "TradeUnitOfQuantity");
                ReportPropertyChanged("TradeUnitOfQuantity");
                OnTradeUnitOfQuantityChanged();
            }
        }
        private global::System.String _TradeUnitOfQuantity;
        partial void OnTradeUnitOfQuantityChanging(global::System.String value);
        partial void OnTradeUnitOfQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ImportExcise
        {
            get
            {
                return _ImportExcise;
            }
            set
            {
                OnImportExciseChanging(value);
                ReportPropertyChanging("ImportExcise");
                _ImportExcise = StructuralObject.SetValidValue(value, "ImportExcise");
                ReportPropertyChanged("ImportExcise");
                OnImportExciseChanged();
            }
        }
        private Nullable<global::System.Decimal> _ImportExcise;
        partial void OnImportExciseChanging(Nullable<global::System.Decimal> value);
        partial void OnImportExciseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AfricanUnionImportlevy
        {
            get
            {
                return _AfricanUnionImportlevy;
            }
            set
            {
                OnAfricanUnionImportlevyChanging(value);
                ReportPropertyChanging("AfricanUnionImportlevy");
                _AfricanUnionImportlevy = StructuralObject.SetValidValue(value, "AfricanUnionImportlevy");
                ReportPropertyChanged("AfricanUnionImportlevy");
                OnAfricanUnionImportlevyChanged();
            }
        }
        private Nullable<global::System.Decimal> _AfricanUnionImportlevy;
        partial void OnAfricanUnionImportlevyChanging(Nullable<global::System.Decimal> value);
        partial void OnAfricanUnionImportlevyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CasseteLevy
        {
            get
            {
                return _CasseteLevy;
            }
            set
            {
                OnCasseteLevyChanging(value);
                ReportPropertyChanging("CasseteLevy");
                _CasseteLevy = StructuralObject.SetValidValue(value, "CasseteLevy");
                ReportPropertyChanged("CasseteLevy");
                OnCasseteLevyChanged();
            }
        }
        private global::System.Decimal _CasseteLevy;
        partial void OnCasseteLevyChanging(global::System.Decimal value);
        partial void OnCasseteLevyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EnvironmentalExcise
        {
            get
            {
                return _EnvironmentalExcise;
            }
            set
            {
                OnEnvironmentalExciseChanging(value);
                ReportPropertyChanging("EnvironmentalExcise");
                _EnvironmentalExcise = StructuralObject.SetValidValue(value, "EnvironmentalExcise");
                ReportPropertyChanged("EnvironmentalExcise");
                OnEnvironmentalExciseChanged();
            }
        }
        private global::System.Decimal _EnvironmentalExcise;
        partial void OnEnvironmentalExciseChanging(global::System.Decimal value);
        partial void OnEnvironmentalExciseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ProcessingFee
        {
            get
            {
                return _ProcessingFee;
            }
            set
            {
                OnProcessingFeeChanging(value);
                ReportPropertyChanging("ProcessingFee");
                _ProcessingFee = StructuralObject.SetValidValue(value, "ProcessingFee");
                ReportPropertyChanged("ProcessingFee");
                OnProcessingFeeChanged();
            }
        }
        private global::System.Decimal _ProcessingFee;
        partial void OnProcessingFeeChanging(global::System.Decimal value);
        partial void OnProcessingFeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ImportLevy
        {
            get
            {
                return _ImportLevy;
            }
            set
            {
                OnImportLevyChanging(value);
                ReportPropertyChanging("ImportLevy");
                _ImportLevy = StructuralObject.SetValidValue(value, "ImportLevy");
                ReportPropertyChanged("ImportLevy");
                OnImportLevyChanged();
            }
        }
        private global::System.Decimal _ImportLevy;
        partial void OnImportLevyChanging(global::System.Decimal value);
        partial void OnImportLevyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GetFund
        {
            get
            {
                return _GetFund;
            }
            set
            {
                OnGetFundChanging(value);
                ReportPropertyChanging("GetFund");
                _GetFund = StructuralObject.SetValidValue(value, "GetFund");
                ReportPropertyChanged("GetFund");
                OnGetFundChanged();
            }
        }
        private global::System.Decimal _GetFund;
        partial void OnGetFundChanging(global::System.Decimal value);
        partial void OnGetFundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImportVatAmended
        {
            get
            {
                return _ImportVatAmended;
            }
            set
            {
                OnImportVatAmendedChanging(value);
                ReportPropertyChanging("ImportVatAmended");
                _ImportVatAmended = StructuralObject.SetValidValue(value, true, "ImportVatAmended");
                ReportPropertyChanged("ImportVatAmended");
                OnImportVatAmendedChanged();
            }
        }
        private global::System.String _ImportVatAmended;
        partial void OnImportVatAmendedChanging(global::System.String value);
        partial void OnImportVatAmendedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GetFund1
        {
            get
            {
                return _GetFund1;
            }
            set
            {
                OnGetFund1Changing(value);
                ReportPropertyChanging("GetFund1");
                _GetFund1 = StructuralObject.SetValidValue(value, true, "GetFund1");
                ReportPropertyChanged("GetFund1");
                OnGetFund1Changed();
            }
        }
        private global::System.String _GetFund1;
        partial void OnGetFund1Changing(global::System.String value);
        partial void OnGetFund1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GetFund2
        {
            get
            {
                return _GetFund2;
            }
            set
            {
                OnGetFund2Changing(value);
                ReportPropertyChanging("GetFund2");
                _GetFund2 = StructuralObject.SetValidValue(value, true, "GetFund2");
                ReportPropertyChanged("GetFund2");
                OnGetFund2Changed();
            }
        }
        private global::System.String _GetFund2;
        partial void OnGetFund2Changing(global::System.String value);
        partial void OnGetFund2Changed();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="sid_FreightRates")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sid_FreightRates : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sid_FreightRates object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="vehicleCategoryId">Initial value of the VehicleCategoryId property.</param>
        public static sid_FreightRates Createsid_FreightRates(global::System.Int32 id, global::System.Int32 vehicleCategoryId)
        {
            sid_FreightRates sid_FreightRates = new sid_FreightRates();
            sid_FreightRates.Id = id;
            sid_FreightRates.VehicleCategoryId = vehicleCategoryId;
            return sid_FreightRates;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VehicleCategoryId
        {
            get
            {
                return _VehicleCategoryId;
            }
            set
            {
                OnVehicleCategoryIdChanging(value);
                ReportPropertyChanging("VehicleCategoryId");
                _VehicleCategoryId = StructuralObject.SetValidValue(value, "VehicleCategoryId");
                ReportPropertyChanged("VehicleCategoryId");
                OnVehicleCategoryIdChanged();
            }
        }
        private global::System.Int32 _VehicleCategoryId;
        partial void OnVehicleCategoryIdChanging(global::System.Int32 value);
        partial void OnVehicleCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FreightRate
        {
            get
            {
                return _FreightRate;
            }
            set
            {
                OnFreightRateChanging(value);
                ReportPropertyChanging("FreightRate");
                _FreightRate = StructuralObject.SetValidValue(value, "FreightRate");
                ReportPropertyChanged("FreightRate");
                OnFreightRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _FreightRate;
        partial void OnFreightRateChanging(Nullable<global::System.Decimal> value);
        partial void OnFreightRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinimumCC
        {
            get
            {
                return _MinimumCC;
            }
            set
            {
                OnMinimumCCChanging(value);
                ReportPropertyChanging("MinimumCC");
                _MinimumCC = StructuralObject.SetValidValue(value, "MinimumCC");
                ReportPropertyChanged("MinimumCC");
                OnMinimumCCChanged();
            }
        }
        private Nullable<global::System.Int32> _MinimumCC;
        partial void OnMinimumCCChanging(Nullable<global::System.Int32> value);
        partial void OnMinimumCCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaximumCC
        {
            get
            {
                return _MaximumCC;
            }
            set
            {
                OnMaximumCCChanging(value);
                ReportPropertyChanging("MaximumCC");
                _MaximumCC = StructuralObject.SetValidValue(value, "MaximumCC");
                ReportPropertyChanged("MaximumCC");
                OnMaximumCCChanged();
            }
        }
        private Nullable<global::System.Int32> _MaximumCC;
        partial void OnMaximumCCChanging(Nullable<global::System.Int32> value);
        partial void OnMaximumCCChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PAARv2Model", "FK_sid_FreightRates_sid_FreightRates", "sid_VehicleCategory")]
        public sid_VehicleCategory sid_VehicleCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_FreightRates_sid_FreightRates", "sid_VehicleCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_FreightRates_sid_FreightRates", "sid_VehicleCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sid_VehicleCategory> sid_VehicleCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_FreightRates_sid_FreightRates", "sid_VehicleCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_FreightRates_sid_FreightRates", "sid_VehicleCategory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="sid_VehicleCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sid_VehicleCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sid_VehicleCategory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static sid_VehicleCategory Createsid_VehicleCategory(global::System.Int32 id)
        {
            sid_VehicleCategory sid_VehicleCategory = new sid_VehicleCategory();
            sid_VehicleCategory.Id = id;
            return sid_VehicleCategory;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PAARv2Model", "FK_sid_FreightRates_sid_FreightRates", "sid_FreightRates")]
        public EntityCollection<sid_FreightRates> sid_FreightRates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sid_FreightRates>("PAARv2Model.FK_sid_FreightRates_sid_FreightRates", "sid_FreightRates");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sid_FreightRates>("PAARv2Model.FK_sid_FreightRates_sid_FreightRates", "sid_FreightRates", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PAARv2Model", "FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleTypes")]
        public EntityCollection<sid_VehicleTypes> sid_VehicleTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sid_VehicleTypes>("PAARv2Model.FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sid_VehicleTypes>("PAARv2Model.FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleTypes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="sid_VehicleTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sid_VehicleTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sid_VehicleTypes object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="typeName">Initial value of the TypeName property.</param>
        public static sid_VehicleTypes Createsid_VehicleTypes(global::System.Int32 id, global::System.String typeName)
        {
            sid_VehicleTypes sid_VehicleTypes = new sid_VehicleTypes();
            sid_VehicleTypes.ID = id;
            sid_VehicleTypes.TypeName = typeName;
            return sid_VehicleTypes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeName
        {
            get
            {
                return _TypeName;
            }
            set
            {
                OnTypeNameChanging(value);
                ReportPropertyChanging("TypeName");
                _TypeName = StructuralObject.SetValidValue(value, false, "TypeName");
                ReportPropertyChanged("TypeName");
                OnTypeNameChanged();
            }
        }
        private global::System.String _TypeName;
        partial void OnTypeNameChanging(global::System.String value);
        partial void OnTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VehicleCategoryId
        {
            get
            {
                return _VehicleCategoryId;
            }
            set
            {
                OnVehicleCategoryIdChanging(value);
                ReportPropertyChanging("VehicleCategoryId");
                _VehicleCategoryId = StructuralObject.SetValidValue(value, "VehicleCategoryId");
                ReportPropertyChanged("VehicleCategoryId");
                OnVehicleCategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _VehicleCategoryId;
        partial void OnVehicleCategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnVehicleCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true, "CreatedBy");
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, "DateCreated");
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, true, "LastModifiedBy");
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value, "LastModifiedDate");
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedDate;
        partial void OnLastModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PAARv2Model", "FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleCategory")]
        public sid_VehicleCategory sid_VehicleCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sid_VehicleCategory> sid_VehicleCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sid_VehicleCategory>("PAARv2Model.FK_sid_VehicleTypes_sid_VehicleCategory", "sid_VehicleCategory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="TariffBenchmark")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TariffBenchmark : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TariffBenchmark object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TariffBenchmark CreateTariffBenchmark(global::System.Int32 id)
        {
            TariffBenchmark tariffBenchmark = new TariffBenchmark();
            tariffBenchmark.Id = id;
            return tariffBenchmark;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HSCode
        {
            get
            {
                return _HSCode;
            }
            set
            {
                OnHSCodeChanging(value);
                ReportPropertyChanging("HSCode");
                _HSCode = StructuralObject.SetValidValue(value, true, "HSCode");
                ReportPropertyChanged("HSCode");
                OnHSCodeChanged();
            }
        }
        private global::System.String _HSCode;
        partial void OnHSCodeChanging(global::System.String value);
        partial void OnHSCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true, "Keywords");
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true, "Country");
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ProductValue
        {
            get
            {
                return _ProductValue;
            }
            set
            {
                OnProductValueChanging(value);
                ReportPropertyChanging("ProductValue");
                _ProductValue = StructuralObject.SetValidValue(value, "ProductValue");
                ReportPropertyChanged("ProductValue");
                OnProductValueChanged();
            }
        }
        private Nullable<global::System.Double> _ProductValue;
        partial void OnProductValueChanging(Nullable<global::System.Double> value);
        partial void OnProductValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Unit
        {
            get
            {
                return _Unit;
            }
            set
            {
                OnUnitChanging(value);
                ReportPropertyChanging("Unit");
                _Unit = StructuralObject.SetValidValue(value, true, "Unit");
                ReportPropertyChanged("Unit");
                OnUnitChanged();
            }
        }
        private global::System.String _Unit;
        partial void OnUnitChanging(global::System.String value);
        partial void OnUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Packaging
        {
            get
            {
                return _Packaging;
            }
            set
            {
                OnPackagingChanging(value);
                ReportPropertyChanging("Packaging");
                _Packaging = StructuralObject.SetValidValue(value, true, "Packaging");
                ReportPropertyChanged("Packaging");
                OnPackagingChanged();
            }
        }
        private global::System.String _Packaging;
        partial void OnPackagingChanging(global::System.String value);
        partial void OnPackagingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                OnQtyChanging(value);
                ReportPropertyChanging("Qty");
                _Qty = StructuralObject.SetValidValue(value, "Qty");
                ReportPropertyChanged("Qty");
                OnQtyChanged();
            }
        }
        private Nullable<global::System.Double> _Qty;
        partial void OnQtyChanging(Nullable<global::System.Double> value);
        partial void OnQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUOM
        {
            get
            {
                return _SUOM;
            }
            set
            {
                OnSUOMChanging(value);
                ReportPropertyChanging("SUOM");
                _SUOM = StructuralObject.SetValidValue(value, true, "SUOM");
                ReportPropertyChanged("SUOM");
                OnSUOMChanged();
            }
        }
        private global::System.String _SUOM;
        partial void OnSUOMChanging(global::System.String value);
        partial void OnSUOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitFOB
        {
            get
            {
                return _UnitFOB;
            }
            set
            {
                OnUnitFOBChanging(value);
                ReportPropertyChanging("UnitFOB");
                _UnitFOB = StructuralObject.SetValidValue(value, "UnitFOB");
                ReportPropertyChanged("UnitFOB");
                OnUnitFOBChanged();
            }
        }
        private Nullable<global::System.Decimal> _UnitFOB;
        partial void OnUnitFOBChanging(Nullable<global::System.Decimal> value);
        partial void OnUnitFOBChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PAARv2Model", Name="ValuationTPD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ValuationTPD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ValuationTPD object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ValuationTPD CreateValuationTPD(global::System.Int32 id)
        {
            ValuationTPD valuationTPD = new ValuationTPD();
            valuationTPD.ID = id;
            return valuationTPD;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Importer
        {
            get
            {
                return _Importer;
            }
            set
            {
                OnImporterChanging(value);
                ReportPropertyChanging("Importer");
                _Importer = StructuralObject.SetValidValue(value, true, "Importer");
                ReportPropertyChanged("Importer");
                OnImporterChanged();
            }
        }
        private global::System.String _Importer;
        partial void OnImporterChanging(global::System.String value);
        partial void OnImporterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImporterTIN
        {
            get
            {
                return _ImporterTIN;
            }
            set
            {
                OnImporterTINChanging(value);
                ReportPropertyChanging("ImporterTIN");
                _ImporterTIN = StructuralObject.SetValidValue(value, true, "ImporterTIN");
                ReportPropertyChanged("ImporterTIN");
                OnImporterTINChanged();
            }
        }
        private global::System.String _ImporterTIN;
        partial void OnImporterTINChanging(global::System.String value);
        partial void OnImporterTINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exporter
        {
            get
            {
                return _Exporter;
            }
            set
            {
                OnExporterChanging(value);
                ReportPropertyChanging("Exporter");
                _Exporter = StructuralObject.SetValidValue(value, true, "Exporter");
                ReportPropertyChanged("Exporter");
                OnExporterChanged();
            }
        }
        private global::System.String _Exporter;
        partial void OnExporterChanging(global::System.String value);
        partial void OnExporterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeclarationDate
        {
            get
            {
                return _DeclarationDate;
            }
            set
            {
                OnDeclarationDateChanging(value);
                ReportPropertyChanging("DeclarationDate");
                _DeclarationDate = StructuralObject.SetValidValue(value, "DeclarationDate");
                ReportPropertyChanged("DeclarationDate");
                OnDeclarationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeclarationDate;
        partial void OnDeclarationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeclarationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, true, "Model");
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Make
        {
            get
            {
                return _Make;
            }
            set
            {
                OnMakeChanging(value);
                ReportPropertyChanging("Make");
                _Make = StructuralObject.SetValidValue(value, true, "Make");
                ReportPropertyChanged("Make");
                OnMakeChanged();
            }
        }
        private global::System.String _Make;
        partial void OnMakeChanging(global::System.String value);
        partial void OnMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChassisNo
        {
            get
            {
                return _ChassisNo;
            }
            set
            {
                OnChassisNoChanging(value);
                ReportPropertyChanging("ChassisNo");
                _ChassisNo = StructuralObject.SetValidValue(value, true, "ChassisNo");
                ReportPropertyChanged("ChassisNo");
                OnChassisNoChanged();
            }
        }
        private global::System.String _ChassisNo;
        partial void OnChassisNoChanging(global::System.String value);
        partial void OnChassisNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssessedHSCode
        {
            get
            {
                return _AssessedHSCode;
            }
            set
            {
                OnAssessedHSCodeChanging(value);
                ReportPropertyChanging("AssessedHSCode");
                _AssessedHSCode = StructuralObject.SetValidValue(value, true, "AssessedHSCode");
                ReportPropertyChanged("AssessedHSCode");
                OnAssessedHSCodeChanged();
            }
        }
        private global::System.String _AssessedHSCode;
        partial void OnAssessedHSCodeChanging(global::System.String value);
        partial void OnAssessedHSCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Condition
        {
            get
            {
                return _Condition;
            }
            set
            {
                OnConditionChanging(value);
                ReportPropertyChanging("Condition");
                _Condition = StructuralObject.SetValidValue(value, true, "Condition");
                ReportPropertyChanged("Condition");
                OnConditionChanged();
            }
        }
        private global::System.String _Condition;
        partial void OnConditionChanging(global::System.String value);
        partial void OnConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpecialFeatures
        {
            get
            {
                return _SpecialFeatures;
            }
            set
            {
                OnSpecialFeaturesChanging(value);
                ReportPropertyChanging("SpecialFeatures");
                _SpecialFeatures = StructuralObject.SetValidValue(value, true, "SpecialFeatures");
                ReportPropertyChanged("SpecialFeatures");
                OnSpecialFeaturesChanged();
            }
        }
        private global::System.String _SpecialFeatures;
        partial void OnSpecialFeaturesChanging(global::System.String value);
        partial void OnSpecialFeaturesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NoOfDoors
        {
            get
            {
                return _NoOfDoors;
            }
            set
            {
                OnNoOfDoorsChanging(value);
                ReportPropertyChanging("NoOfDoors");
                _NoOfDoors = StructuralObject.SetValidValue(value, "NoOfDoors");
                ReportPropertyChanged("NoOfDoors");
                OnNoOfDoorsChanged();
            }
        }
        private Nullable<global::System.Int32> _NoOfDoors;
        partial void OnNoOfDoorsChanging(Nullable<global::System.Int32> value);
        partial void OnNoOfDoorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ManufactureYear
        {
            get
            {
                return _ManufactureYear;
            }
            set
            {
                OnManufactureYearChanging(value);
                ReportPropertyChanging("ManufactureYear");
                _ManufactureYear = StructuralObject.SetValidValue(value, true, "ManufactureYear");
                ReportPropertyChanged("ManufactureYear");
                OnManufactureYearChanged();
            }
        }
        private global::System.String _ManufactureYear;
        partial void OnManufactureYearChanging(global::System.String value);
        partial void OnManufactureYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EngineCapacity
        {
            get
            {
                return _EngineCapacity;
            }
            set
            {
                OnEngineCapacityChanging(value);
                ReportPropertyChanging("EngineCapacity");
                _EngineCapacity = StructuralObject.SetValidValue(value, true, "EngineCapacity");
                ReportPropertyChanged("EngineCapacity");
                OnEngineCapacityChanged();
            }
        }
        private global::System.String _EngineCapacity;
        partial void OnEngineCapacityChanging(global::System.String value);
        partial void OnEngineCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HDV
        {
            get
            {
                return _HDV;
            }
            set
            {
                OnHDVChanging(value);
                ReportPropertyChanging("HDV");
                _HDV = StructuralObject.SetValidValue(value, "HDV");
                ReportPropertyChanged("HDV");
                OnHDVChanged();
            }
        }
        private Nullable<global::System.Decimal> _HDV;
        partial void OnHDVChanging(Nullable<global::System.Decimal> value);
        partial void OnHDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VehicleType
        {
            get
            {
                return _VehicleType;
            }
            set
            {
                OnVehicleTypeChanging(value);
                ReportPropertyChanging("VehicleType");
                _VehicleType = StructuralObject.SetValidValue(value, true, "VehicleType");
                ReportPropertyChanged("VehicleType");
                OnVehicleTypeChanged();
            }
        }
        private global::System.String _VehicleType;
        partial void OnVehicleTypeChanging(global::System.String value);
        partial void OnVehicleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true, "Currency");
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAARNo
        {
            get
            {
                return _PAARNo;
            }
            set
            {
                OnPAARNoChanging(value);
                ReportPropertyChanging("PAARNo");
                _PAARNo = StructuralObject.SetValidValue(value, true, "PAARNo");
                ReportPropertyChanged("PAARNo");
                OnPAARNoChanged();
            }
        }
        private global::System.String _PAARNo;
        partial void OnPAARNoChanging(global::System.String value);
        partial void OnPAARNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PAARIssueDate
        {
            get
            {
                return _PAARIssueDate;
            }
            set
            {
                OnPAARIssueDateChanging(value);
                ReportPropertyChanging("PAARIssueDate");
                _PAARIssueDate = StructuralObject.SetValidValue(value, "PAARIssueDate");
                ReportPropertyChanged("PAARIssueDate");
                OnPAARIssueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PAARIssueDate;
        partial void OnPAARIssueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPAARIssueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeatingCapacity
        {
            get
            {
                return _SeatingCapacity;
            }
            set
            {
                OnSeatingCapacityChanging(value);
                ReportPropertyChanging("SeatingCapacity");
                _SeatingCapacity = StructuralObject.SetValidValue(value, "SeatingCapacity");
                ReportPropertyChanged("SeatingCapacity");
                OnSeatingCapacityChanged();
            }
        }
        private Nullable<global::System.Int32> _SeatingCapacity;
        partial void OnSeatingCapacityChanging(Nullable<global::System.Int32> value);
        partial void OnSeatingCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FuelType
        {
            get
            {
                return _FuelType;
            }
            set
            {
                OnFuelTypeChanging(value);
                ReportPropertyChanging("FuelType");
                _FuelType = StructuralObject.SetValidValue(value, true, "FuelType");
                ReportPropertyChanged("FuelType");
                OnFuelTypeChanged();
            }
        }
        private global::System.String _FuelType;
        partial void OnFuelTypeChanging(global::System.String value);
        partial void OnFuelTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Colour
        {
            get
            {
                return _Colour;
            }
            set
            {
                OnColourChanging(value);
                ReportPropertyChanging("Colour");
                _Colour = StructuralObject.SetValidValue(value, true, "Colour");
                ReportPropertyChanged("Colour");
                OnColourChanged();
            }
        }
        private global::System.String _Colour;
        partial void OnColourChanging(global::System.String value);
        partial void OnColourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion

    }

    #endregion

}
