//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ClassificationToolsModel", "FK_HSCodes_HSCodes", "HSCodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Classification.DAL.HSCodes), "HSCodes1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Classification.DAL.HSCodes), true)]

#endregion

namespace Classification.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClassificationToolsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClassificationToolsEntities object using the connection string found in the 'ClassificationToolsEntities' section of the application configuration file.
        /// </summary>
        public ClassificationToolsEntities() : base("name=ClassificationToolsEntities", "ClassificationToolsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClassificationToolsEntities object.
        /// </summary>
        public ClassificationToolsEntities(string connectionString) : base(connectionString, "ClassificationToolsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClassificationToolsEntities object.
        /// </summary>
        public ClassificationToolsEntities(EntityConnection connection) : base(connection, "ClassificationToolsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DutyCalculatorFeedback> DutyCalculatorFeedback
        {
            get
            {
                if ((_DutyCalculatorFeedback == null))
                {
                    _DutyCalculatorFeedback = base.CreateObjectSet<DutyCalculatorFeedback>("DutyCalculatorFeedback");
                }
                return _DutyCalculatorFeedback;
            }
        }
        private ObjectSet<DutyCalculatorFeedback> _DutyCalculatorFeedback;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HitCounter> HitCounter
        {
            get
            {
                if ((_HitCounter == null))
                {
                    _HitCounter = base.CreateObjectSet<HitCounter>("HitCounter");
                }
                return _HitCounter;
            }
        }
        private ObjectSet<HitCounter> _HitCounter;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HSCodes> HSCodes
        {
            get
            {
                if ((_HSCodes == null))
                {
                    _HSCodes = base.CreateObjectSet<HSCodes>("HSCodes");
                }
                return _HSCodes;
            }
        }
        private ObjectSet<HSCodes> _HSCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExchangeRate> ExchangeRate
        {
            get
            {
                if ((_ExchangeRate == null))
                {
                    _ExchangeRate = base.CreateObjectSet<ExchangeRate>("ExchangeRate");
                }
                return _ExchangeRate;
            }
        }
        private ObjectSet<ExchangeRate> _ExchangeRate;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_FreightOverage> v_FreightOverage
        {
            get
            {
                if ((_v_FreightOverage == null))
                {
                    _v_FreightOverage = base.CreateObjectSet<v_FreightOverage>("v_FreightOverage");
                }
                return _v_FreightOverage;
            }
        }
        private ObjectSet<v_FreightOverage> _v_FreightOverage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_VehicleType> v_VehicleType
        {
            get
            {
                if ((_v_VehicleType == null))
                {
                    _v_VehicleType = base.CreateObjectSet<v_VehicleType>("v_VehicleType");
                }
                return _v_VehicleType;
            }
        }
        private ObjectSet<v_VehicleType> _v_VehicleType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_VehicleValue> V_VehicleValue
        {
            get
            {
                if ((_V_VehicleValue == null))
                {
                    _V_VehicleValue = base.CreateObjectSet<V_VehicleValue>("V_VehicleValue");
                }
                return _V_VehicleValue;
            }
        }
        private ObjectSet<V_VehicleValue> _V_VehicleValue;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DutyCalculatorFeedback EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDutyCalculatorFeedback(DutyCalculatorFeedback dutyCalculatorFeedback)
        {
            base.AddObject("DutyCalculatorFeedback", dutyCalculatorFeedback);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HitCounter EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHitCounter(HitCounter hitCounter)
        {
            base.AddObject("HitCounter", hitCounter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HSCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHSCodes(HSCodes hSCodes)
        {
            base.AddObject("HSCodes", hSCodes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExchangeRate EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExchangeRate(ExchangeRate exchangeRate)
        {
            base.AddObject("ExchangeRate", exchangeRate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_FreightOverage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_FreightOverage(v_FreightOverage v_FreightOverage)
        {
            base.AddObject("v_FreightOverage", v_FreightOverage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_VehicleType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_VehicleType(v_VehicleType v_VehicleType)
        {
            base.AddObject("v_VehicleType", v_VehicleType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_VehicleValue EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_VehicleValue(V_VehicleValue v_VehicleValue)
        {
            base.AddObject("V_VehicleValue", v_VehicleValue);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="DutyCalculatorFeedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DutyCalculatorFeedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DutyCalculatorFeedback object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sendDate">Initial value of the SendDate property.</param>
        public static DutyCalculatorFeedback CreateDutyCalculatorFeedback(global::System.Int32 id, global::System.DateTime sendDate)
        {
            DutyCalculatorFeedback dutyCalculatorFeedback = new DutyCalculatorFeedback();
            dutyCalculatorFeedback.Id = id;
            dutyCalculatorFeedback.SendDate = sendDate;
            return dutyCalculatorFeedback;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendDate
        {
            get
            {
                return _SendDate;
            }
            set
            {
                OnSendDateChanging(value);
                ReportPropertyChanging("SendDate");
                _SendDate = StructuralObject.SetValidValue(value, "SendDate");
                ReportPropertyChanged("SendDate");
                OnSendDateChanged();
            }
        }
        private global::System.DateTime _SendDate;
        partial void OnSendDateChanging(global::System.DateTime value);
        partial void OnSendDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true, "Message");
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true, "FullName");
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true, "EmailAddress");
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="ExchangeRate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExchangeRate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExchangeRate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="week">Initial value of the Week property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static ExchangeRate CreateExchangeRate(global::System.Int32 id, global::System.DateTime week, global::System.Decimal rate)
        {
            ExchangeRate exchangeRate = new ExchangeRate();
            exchangeRate.Id = id;
            exchangeRate.Week = week;
            exchangeRate.Rate = rate;
            return exchangeRate;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Week
        {
            get
            {
                return _Week;
            }
            set
            {
                if (_Week != value)
                {
                    OnWeekChanging(value);
                    ReportPropertyChanging("Week");
                    _Week = StructuralObject.SetValidValue(value, "Week");
                    ReportPropertyChanged("Week");
                    OnWeekChanged();
                }
            }
        }
        private global::System.DateTime _Week;
        partial void OnWeekChanging(global::System.DateTime value);
        partial void OnWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrencyCode
        {
            get
            {
                return _CurrencyCode;
            }
            set
            {
                OnCurrencyCodeChanging(value);
                ReportPropertyChanging("CurrencyCode");
                _CurrencyCode = StructuralObject.SetValidValue(value, true, "CurrencyCode");
                ReportPropertyChanged("CurrencyCode");
                OnCurrencyCodeChanged();
            }
        }
        private global::System.String _CurrencyCode;
        partial void OnCurrencyCodeChanging(global::System.String value);
        partial void OnCurrencyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                if (_Rate != value)
                {
                    OnRateChanging(value);
                    ReportPropertyChanging("Rate");
                    _Rate = StructuralObject.SetValidValue(value, "Rate");
                    ReportPropertyChanged("Rate");
                    OnRateChanged();
                }
            }
        }
        private global::System.Decimal _Rate;
        partial void OnRateChanging(global::System.Decimal value);
        partial void OnRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value, "ModifiedDate");
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true, "ModifiedBy");
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="HitCounter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HitCounter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HitCounter object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="counter">Initial value of the Counter property.</param>
        public static HitCounter CreateHitCounter(global::System.Int32 id, global::System.Int32 counter)
        {
            HitCounter hitCounter = new HitCounter();
            hitCounter.Id = id;
            hitCounter.Counter = counter;
            return hitCounter;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Counter
        {
            get
            {
                return _Counter;
            }
            set
            {
                OnCounterChanging(value);
                ReportPropertyChanging("Counter");
                _Counter = StructuralObject.SetValidValue(value, "Counter");
                ReportPropertyChanged("Counter");
                OnCounterChanged();
            }
        }
        private global::System.Int32 _Counter;
        partial void OnCounterChanging(global::System.Int32 value);
        partial void OnCounterChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="HSCodes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HSCodes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HSCodes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="chapter">Initial value of the Chapter property.</param>
        /// <param name="isChapter">Initial value of the IsChapter property.</param>
        /// <param name="isSubChapter">Initial value of the IsSubChapter property.</param>
        /// <param name="isSubHeader">Initial value of the IsSubHeader property.</param>
        public static HSCodes CreateHSCodes(global::System.Int32 id, global::System.Int32 chapter, global::System.Boolean isChapter, global::System.Boolean isSubChapter, global::System.Boolean isSubHeader)
        {
            HSCodes hSCodes = new HSCodes();
            hSCodes.Id = id;
            hSCodes.Chapter = chapter;
            hSCodes.IsChapter = isChapter;
            hSCodes.IsSubChapter = isSubChapter;
            hSCodes.IsSubHeader = isSubHeader;
            return hSCodes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value, "ParentId");
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Heading
        {
            get
            {
                return _Heading;
            }
            set
            {
                OnHeadingChanging(value);
                ReportPropertyChanging("Heading");
                _Heading = StructuralObject.SetValidValue(value, true, "Heading");
                ReportPropertyChanged("Heading");
                OnHeadingChanged();
            }
        }
        private global::System.String _Heading;
        partial void OnHeadingChanging(global::System.String value);
        partial void OnHeadingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Chapter
        {
            get
            {
                return _Chapter;
            }
            set
            {
                OnChapterChanging(value);
                ReportPropertyChanging("Chapter");
                _Chapter = StructuralObject.SetValidValue(value, "Chapter");
                ReportPropertyChanged("Chapter");
                OnChapterChanged();
            }
        }
        private global::System.Int32 _Chapter;
        partial void OnChapterChanging(global::System.Int32 value);
        partial void OnChapterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ImportDuty
        {
            get
            {
                return _ImportDuty;
            }
            set
            {
                OnImportDutyChanging(value);
                ReportPropertyChanging("ImportDuty");
                _ImportDuty = StructuralObject.SetValidValue(value, "ImportDuty");
                ReportPropertyChanged("ImportDuty");
                OnImportDutyChanged();
            }
        }
        private Nullable<global::System.Decimal> _ImportDuty;
        partial void OnImportDutyChanging(Nullable<global::System.Decimal> value);
        partial void OnImportDutyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> VAT
        {
            get
            {
                return _VAT;
            }
            set
            {
                OnVATChanging(value);
                ReportPropertyChanging("VAT");
                _VAT = StructuralObject.SetValidValue(value, "VAT");
                ReportPropertyChanged("VAT");
                OnVATChanged();
            }
        }
        private Nullable<global::System.Decimal> _VAT;
        partial void OnVATChanging(Nullable<global::System.Decimal> value);
        partial void OnVATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NHIL
        {
            get
            {
                return _NHIL;
            }
            set
            {
                OnNHILChanging(value);
                ReportPropertyChanging("NHIL");
                _NHIL = StructuralObject.SetValidValue(value, "NHIL");
                ReportPropertyChanged("NHIL");
                OnNHILChanged();
            }
        }
        private Nullable<global::System.Decimal> _NHIL;
        partial void OnNHILChanging(Nullable<global::System.Decimal> value);
        partial void OnNHILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ImportExcise
        {
            get
            {
                return _ImportExcise;
            }
            set
            {
                OnImportExciseChanging(value);
                ReportPropertyChanging("ImportExcise");
                _ImportExcise = StructuralObject.SetValidValue(value, "ImportExcise");
                ReportPropertyChanged("ImportExcise");
                OnImportExciseChanged();
            }
        }
        private Nullable<global::System.Decimal> _ImportExcise;
        partial void OnImportExciseChanging(Nullable<global::System.Decimal> value);
        partial void OnImportExciseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OveragePenalty
        {
            get
            {
                return _OveragePenalty;
            }
            set
            {
                OnOveragePenaltyChanging(value);
                ReportPropertyChanging("OveragePenalty");
                _OveragePenalty = StructuralObject.SetValidValue(value, "OveragePenalty");
                ReportPropertyChanged("OveragePenalty");
                OnOveragePenaltyChanged();
            }
        }
        private Nullable<global::System.Decimal> _OveragePenalty;
        partial void OnOveragePenaltyChanging(Nullable<global::System.Decimal> value);
        partial void OnOveragePenaltyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExportDuty
        {
            get
            {
                return _ExportDuty;
            }
            set
            {
                OnExportDutyChanging(value);
                ReportPropertyChanging("ExportDuty");
                _ExportDuty = StructuralObject.SetValidValue(value, true, "ExportDuty");
                ReportPropertyChanged("ExportDuty");
                OnExportDutyChanged();
            }
        }
        private global::System.String _ExportDuty;
        partial void OnExportDutyChanging(global::System.String value);
        partial void OnExportDutyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StandardUOQ
        {
            get
            {
                return _StandardUOQ;
            }
            set
            {
                OnStandardUOQChanging(value);
                ReportPropertyChanging("StandardUOQ");
                _StandardUOQ = StructuralObject.SetValidValue(value, true, "StandardUOQ");
                ReportPropertyChanged("StandardUOQ");
                OnStandardUOQChanged();
            }
        }
        private global::System.String _StandardUOQ;
        partial void OnStandardUOQChanging(global::System.String value);
        partial void OnStandardUOQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsChapter
        {
            get
            {
                return _IsChapter;
            }
            set
            {
                OnIsChapterChanging(value);
                ReportPropertyChanging("IsChapter");
                _IsChapter = StructuralObject.SetValidValue(value, "IsChapter");
                ReportPropertyChanged("IsChapter");
                OnIsChapterChanged();
            }
        }
        private global::System.Boolean _IsChapter;
        partial void OnIsChapterChanging(global::System.Boolean value);
        partial void OnIsChapterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSubChapter
        {
            get
            {
                return _IsSubChapter;
            }
            set
            {
                OnIsSubChapterChanging(value);
                ReportPropertyChanging("IsSubChapter");
                _IsSubChapter = StructuralObject.SetValidValue(value, "IsSubChapter");
                ReportPropertyChanged("IsSubChapter");
                OnIsSubChapterChanged();
            }
        }
        private global::System.Boolean _IsSubChapter;
        partial void OnIsSubChapterChanging(global::System.Boolean value);
        partial void OnIsSubChapterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SectionId
        {
            get
            {
                return _SectionId;
            }
            set
            {
                OnSectionIdChanging(value);
                ReportPropertyChanging("SectionId");
                _SectionId = StructuralObject.SetValidValue(value, "SectionId");
                ReportPropertyChanged("SectionId");
                OnSectionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SectionId;
        partial void OnSectionIdChanging(Nullable<global::System.Int32> value);
        partial void OnSectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSubHeader
        {
            get
            {
                return _IsSubHeader;
            }
            set
            {
                OnIsSubHeaderChanging(value);
                ReportPropertyChanging("IsSubHeader");
                _IsSubHeader = StructuralObject.SetValidValue(value, "IsSubHeader");
                ReportPropertyChanged("IsSubHeader");
                OnIsSubHeaderChanged();
            }
        }
        private global::System.Boolean _IsSubHeader;
        partial void OnIsSubHeaderChanging(global::System.Boolean value);
        partial void OnIsSubHeaderChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassificationToolsModel", "FK_HSCodes_HSCodes", "HSCodes1")]
        public EntityCollection<HSCodes> HSCodes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HSCodes>("ClassificationToolsModel.FK_HSCodes_HSCodes", "HSCodes1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HSCodes>("ClassificationToolsModel.FK_HSCodes_HSCodes", "HSCodes1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassificationToolsModel", "FK_HSCodes_HSCodes", "HSCodes")]
        public HSCodes HSCodes2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HSCodes>("ClassificationToolsModel.FK_HSCodes_HSCodes", "HSCodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HSCodes>("ClassificationToolsModel.FK_HSCodes_HSCodes", "HSCodes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HSCodes> HSCodes2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HSCodes>("ClassificationToolsModel.FK_HSCodes_HSCodes", "HSCodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HSCodes>("ClassificationToolsModel.FK_HSCodes_HSCodes", "HSCodes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="v_FreightOverage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_FreightOverage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_FreightOverage object.
        /// </summary>
        /// <param name="typename">Initial value of the typename property.</param>
        public static v_FreightOverage Createv_FreightOverage(global::System.String typename)
        {
            v_FreightOverage v_FreightOverage = new v_FreightOverage();
            v_FreightOverage.typename = typename;
            return v_FreightOverage;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String typename
        {
            get
            {
                return _typename;
            }
            set
            {
                if (_typename != value)
                {
                    OntypenameChanging(value);
                    ReportPropertyChanging("typename");
                    _typename = StructuralObject.SetValidValue(value, false, "typename");
                    ReportPropertyChanged("typename");
                    OntypenameChanged();
                }
            }
        }
        private global::System.String _typename;
        partial void OntypenameChanging(global::System.String value);
        partial void OntypenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String overagename
        {
            get
            {
                return _overagename;
            }
            set
            {
                OnoveragenameChanging(value);
                ReportPropertyChanging("overagename");
                _overagename = StructuralObject.SetValidValue(value, true, "overagename");
                ReportPropertyChanged("overagename");
                OnoveragenameChanged();
            }
        }
        private global::System.String _overagename;
        partial void OnoveragenameChanging(global::System.String value);
        partial void OnoveragenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OverAgeRate
        {
            get
            {
                return _OverAgeRate;
            }
            set
            {
                OnOverAgeRateChanging(value);
                ReportPropertyChanging("OverAgeRate");
                _OverAgeRate = StructuralObject.SetValidValue(value, "OverAgeRate");
                ReportPropertyChanged("OverAgeRate");
                OnOverAgeRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _OverAgeRate;
        partial void OnOverAgeRateChanging(Nullable<global::System.Decimal> value);
        partial void OnOverAgeRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinimumAge
        {
            get
            {
                return _MinimumAge;
            }
            set
            {
                OnMinimumAgeChanging(value);
                ReportPropertyChanging("MinimumAge");
                _MinimumAge = StructuralObject.SetValidValue(value, "MinimumAge");
                ReportPropertyChanged("MinimumAge");
                OnMinimumAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _MinimumAge;
        partial void OnMinimumAgeChanging(Nullable<global::System.Int32> value);
        partial void OnMinimumAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaximumAge
        {
            get
            {
                return _MaximumAge;
            }
            set
            {
                OnMaximumAgeChanging(value);
                ReportPropertyChanging("MaximumAge");
                _MaximumAge = StructuralObject.SetValidValue(value, "MaximumAge");
                ReportPropertyChanged("MaximumAge");
                OnMaximumAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _MaximumAge;
        partial void OnMaximumAgeChanging(Nullable<global::System.Int32> value);
        partial void OnMaximumAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String freightname
        {
            get
            {
                return _freightname;
            }
            set
            {
                OnfreightnameChanging(value);
                ReportPropertyChanging("freightname");
                _freightname = StructuralObject.SetValidValue(value, true, "freightname");
                ReportPropertyChanged("freightname");
                OnfreightnameChanged();
            }
        }
        private global::System.String _freightname;
        partial void OnfreightnameChanging(global::System.String value);
        partial void OnfreightnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> freightrate
        {
            get
            {
                return _freightrate;
            }
            set
            {
                OnfreightrateChanging(value);
                ReportPropertyChanging("freightrate");
                _freightrate = StructuralObject.SetValidValue(value, "freightrate");
                ReportPropertyChanged("freightrate");
                OnfreightrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _freightrate;
        partial void OnfreightrateChanging(Nullable<global::System.Decimal> value);
        partial void OnfreightrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> minimumcc
        {
            get
            {
                return _minimumcc;
            }
            set
            {
                OnminimumccChanging(value);
                ReportPropertyChanging("minimumcc");
                _minimumcc = StructuralObject.SetValidValue(value, "minimumcc");
                ReportPropertyChanged("minimumcc");
                OnminimumccChanged();
            }
        }
        private Nullable<global::System.Int32> _minimumcc;
        partial void OnminimumccChanging(Nullable<global::System.Int32> value);
        partial void OnminimumccChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> maximumcc
        {
            get
            {
                return _maximumcc;
            }
            set
            {
                OnmaximumccChanging(value);
                ReportPropertyChanging("maximumcc");
                _maximumcc = StructuralObject.SetValidValue(value, "maximumcc");
                ReportPropertyChanged("maximumcc");
                OnmaximumccChanged();
            }
        }
        private Nullable<global::System.Int32> _maximumcc;
        partial void OnmaximumccChanging(Nullable<global::System.Int32> value);
        partial void OnmaximumccChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hscode
        {
            get
            {
                return _hscode;
            }
            set
            {
                OnhscodeChanging(value);
                ReportPropertyChanging("hscode");
                _hscode = StructuralObject.SetValidValue(value, true, "hscode");
                ReportPropertyChanged("hscode");
                OnhscodeChanged();
            }
        }
        private global::System.String _hscode;
        partial void OnhscodeChanging(global::System.String value);
        partial void OnhscodeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="v_VehicleType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_VehicleType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_VehicleType object.
        /// </summary>
        /// <param name="typename">Initial value of the typename property.</param>
        public static v_VehicleType Createv_VehicleType(global::System.String typename)
        {
            v_VehicleType v_VehicleType = new v_VehicleType();
            v_VehicleType.typename = typename;
            return v_VehicleType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String typename
        {
            get
            {
                return _typename;
            }
            set
            {
                if (_typename != value)
                {
                    OntypenameChanging(value);
                    ReportPropertyChanging("typename");
                    _typename = StructuralObject.SetValidValue(value, false, "typename");
                    ReportPropertyChanged("typename");
                    OntypenameChanged();
                }
            }
        }
        private global::System.String _typename;
        partial void OntypenameChanging(global::System.String value);
        partial void OntypenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> enginecapacity
        {
            get
            {
                return _enginecapacity;
            }
            set
            {
                OnenginecapacityChanging(value);
                ReportPropertyChanging("enginecapacity");
                _enginecapacity = StructuralObject.SetValidValue(value, "enginecapacity");
                ReportPropertyChanged("enginecapacity");
                OnenginecapacityChanged();
            }
        }
        private Nullable<global::System.Int32> _enginecapacity;
        partial void OnenginecapacityChanging(Nullable<global::System.Int32> value);
        partial void OnenginecapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String assessedhscode
        {
            get
            {
                return _assessedhscode;
            }
            set
            {
                OnassessedhscodeChanging(value);
                ReportPropertyChanging("assessedhscode");
                _assessedhscode = StructuralObject.SetValidValue(value, true, "assessedhscode");
                ReportPropertyChanged("assessedhscode");
                OnassessedhscodeChanged();
            }
        }
        private global::System.String _assessedhscode;
        partial void OnassessedhscodeChanging(global::System.String value);
        partial void OnassessedhscodeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassificationToolsModel", Name="V_VehicleValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_VehicleValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_VehicleValue object.
        /// </summary>
        /// <param name="vModel">Initial value of the vModel property.</param>
        public static V_VehicleValue CreateV_VehicleValue(global::System.String vModel)
        {
            V_VehicleValue v_VehicleValue = new V_VehicleValue();
            v_VehicleValue.vModel = vModel;
            return v_VehicleValue;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vModel
        {
            get
            {
                return _vModel;
            }
            set
            {
                if (_vModel != value)
                {
                    OnvModelChanging(value);
                    ReportPropertyChanging("vModel");
                    _vModel = StructuralObject.SetValidValue(value, false, "vModel");
                    ReportPropertyChanged("vModel");
                    OnvModelChanged();
                }
            }
        }
        private global::System.String _vModel;
        partial void OnvModelChanging(global::System.String value);
        partial void OnvModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vMake
        {
            get
            {
                return _vMake;
            }
            set
            {
                OnvMakeChanging(value);
                ReportPropertyChanging("vMake");
                _vMake = StructuralObject.SetValidValue(value, true, "vMake");
                ReportPropertyChanged("vMake");
                OnvMakeChanged();
            }
        }
        private global::System.String _vMake;
        partial void OnvMakeChanging(global::System.String value);
        partial void OnvMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vYear
        {
            get
            {
                return _vYear;
            }
            set
            {
                OnvYearChanging(value);
                ReportPropertyChanging("vYear");
                _vYear = StructuralObject.SetValidValue(value, "vYear");
                ReportPropertyChanged("vYear");
                OnvYearChanged();
            }
        }
        private Nullable<global::System.Int32> _vYear;
        partial void OnvYearChanging(Nullable<global::System.Int32> value);
        partial void OnvYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EngineCapacity
        {
            get
            {
                return _EngineCapacity;
            }
            set
            {
                OnEngineCapacityChanging(value);
                ReportPropertyChanging("EngineCapacity");
                _EngineCapacity = StructuralObject.SetValidValue(value, "EngineCapacity");
                ReportPropertyChanged("EngineCapacity");
                OnEngineCapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _EngineCapacity;
        partial void OnEngineCapacityChanging(Nullable<global::System.Decimal> value);
        partial void OnEngineCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HDV
        {
            get
            {
                return _HDV;
            }
            set
            {
                OnHDVChanging(value);
                ReportPropertyChanging("HDV");
                _HDV = StructuralObject.SetValidValue(value, "HDV");
                ReportPropertyChanged("HDV");
                OnHDVChanged();
            }
        }
        private Nullable<global::System.Decimal> _HDV;
        partial void OnHDVChanging(Nullable<global::System.Decimal> value);
        partial void OnHDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VehicleType
        {
            get
            {
                return _VehicleType;
            }
            set
            {
                OnVehicleTypeChanging(value);
                ReportPropertyChanging("VehicleType");
                _VehicleType = StructuralObject.SetValidValue(value, true, "VehicleType");
                ReportPropertyChanged("VehicleType");
                OnVehicleTypeChanged();
            }
        }
        private global::System.String _VehicleType;
        partial void OnVehicleTypeChanging(global::System.String value);
        partial void OnVehicleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true, "Currency");
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, "Id");
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Id;
        partial void OnIdChanging(Nullable<global::System.Int32> value);
        partial void OnIdChanged();

        #endregion

    }

    #endregion

}
