//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CHAMS.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CHAMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CHAMSEntities object using the connection string found in the 'CHAMSEntities' section of the application configuration file.
        /// </summary>
        public CHAMSEntities() : base("name=CHAMSEntities", "CHAMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CHAMSEntities object.
        /// </summary>
        public CHAMSEntities(string connectionString) : base(connectionString, "CHAMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CHAMSEntities object.
        /// </summary>
        public CHAMSEntities(EntityConnection connection) : base(connection, "CHAMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AlertNotification> AlertNotification
        {
            get
            {
                if ((_AlertNotification == null))
                {
                    _AlertNotification = base.CreateObjectSet<AlertNotification>("AlertNotification");
                }
                return _AlertNotification;
            }
        }
        private ObjectSet<AlertNotification> _AlertNotification;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Alert> Alert
        {
            get
            {
                if ((_Alert == null))
                {
                    _Alert = base.CreateObjectSet<Alert>("Alert");
                }
                return _Alert;
            }
        }
        private ObjectSet<Alert> _Alert;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AlertNotification EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlertNotification(AlertNotification alertNotification)
        {
            base.AddObject("AlertNotification", alertNotification);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Alert EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlert(Alert alert)
        {
            base.AddObject("Alert", alert);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CHAMSModel", Name="Alert")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alert : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Alert object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="workFlowId">Initial value of the WorkFlowId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
        public static Alert CreateAlert(global::System.Int32 id, global::System.Int32 workFlowId, global::System.String title, global::System.String modifiedBy, global::System.DateTime modifiedDate)
        {
            Alert alert = new Alert();
            alert.Id = id;
            alert.WorkFlowId = workFlowId;
            alert.Title = title;
            alert.ModifiedBy = modifiedBy;
            alert.ModifiedDate = modifiedDate;
            return alert;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkFlowId
        {
            get
            {
                return _WorkFlowId;
            }
            set
            {
                OnWorkFlowIdChanging(value);
                ReportPropertyChanging("WorkFlowId");
                _WorkFlowId = StructuralObject.SetValidValue(value, "WorkFlowId");
                ReportPropertyChanged("WorkFlowId");
                OnWorkFlowIdChanged();
            }
        }
        private global::System.Int32 _WorkFlowId;
        partial void OnWorkFlowIdChanging(global::System.Int32 value);
        partial void OnWorkFlowIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CCSms
        {
            get
            {
                return _CCSms;
            }
            set
            {
                OnCCSmsChanging(value);
                ReportPropertyChanging("CCSms");
                _CCSms = StructuralObject.SetValidValue(value, true, "CCSms");
                ReportPropertyChanged("CCSms");
                OnCCSmsChanged();
            }
        }
        private global::System.String _CCSms;
        partial void OnCCSmsChanging(global::System.String value);
        partial void OnCCSmsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CCEmail
        {
            get
            {
                return _CCEmail;
            }
            set
            {
                OnCCEmailChanging(value);
                ReportPropertyChanging("CCEmail");
                _CCEmail = StructuralObject.SetValidValue(value, true, "CCEmail");
                ReportPropertyChanged("CCEmail");
                OnCCEmailChanged();
            }
        }
        private global::System.String _CCEmail;
        partial void OnCCEmailChanging(global::System.String value);
        partial void OnCCEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CCNotification
        {
            get
            {
                return _CCNotification;
            }
            set
            {
                OnCCNotificationChanging(value);
                ReportPropertyChanging("CCNotification");
                _CCNotification = StructuralObject.SetValidValue(value, true, "CCNotification");
                ReportPropertyChanged("CCNotification");
                OnCCNotificationChanged();
            }
        }
        private global::System.String _CCNotification;
        partial void OnCCNotificationChanging(global::System.String value);
        partial void OnCCNotificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubjectSms
        {
            get
            {
                return _SubjectSms;
            }
            set
            {
                OnSubjectSmsChanging(value);
                ReportPropertyChanging("SubjectSms");
                _SubjectSms = StructuralObject.SetValidValue(value, true, "SubjectSms");
                ReportPropertyChanged("SubjectSms");
                OnSubjectSmsChanged();
            }
        }
        private global::System.String _SubjectSms;
        partial void OnSubjectSmsChanging(global::System.String value);
        partial void OnSubjectSmsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubjectEmail
        {
            get
            {
                return _SubjectEmail;
            }
            set
            {
                OnSubjectEmailChanging(value);
                ReportPropertyChanging("SubjectEmail");
                _SubjectEmail = StructuralObject.SetValidValue(value, true, "SubjectEmail");
                ReportPropertyChanged("SubjectEmail");
                OnSubjectEmailChanged();
            }
        }
        private global::System.String _SubjectEmail;
        partial void OnSubjectEmailChanging(global::System.String value);
        partial void OnSubjectEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubjectNotification
        {
            get
            {
                return _SubjectNotification;
            }
            set
            {
                OnSubjectNotificationChanging(value);
                ReportPropertyChanging("SubjectNotification");
                _SubjectNotification = StructuralObject.SetValidValue(value, true, "SubjectNotification");
                ReportPropertyChanged("SubjectNotification");
                OnSubjectNotificationChanged();
            }
        }
        private global::System.String _SubjectNotification;
        partial void OnSubjectNotificationChanging(global::System.String value);
        partial void OnSubjectNotificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sms
        {
            get
            {
                return _Sms;
            }
            set
            {
                OnSmsChanging(value);
                ReportPropertyChanging("Sms");
                _Sms = StructuralObject.SetValidValue(value, true, "Sms");
                ReportPropertyChanged("Sms");
                OnSmsChanged();
            }
        }
        private global::System.String _Sms;
        partial void OnSmsChanging(global::System.String value);
        partial void OnSmsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notification
        {
            get
            {
                return _Notification;
            }
            set
            {
                OnNotificationChanging(value);
                ReportPropertyChanging("Notification");
                _Notification = StructuralObject.SetValidValue(value, true, "Notification");
                ReportPropertyChanged("Notification");
                OnNotificationChanged();
            }
        }
        private global::System.String _Notification;
        partial void OnNotificationChanging(global::System.String value);
        partial void OnNotificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, false, "ModifiedBy");
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value, "ModifiedDate");
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value, "EndDate");
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CHAMSModel", Name="AlertNotification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AlertNotification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AlertNotification object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sender">Initial value of the Sender property.</param>
        /// <param name="receiver">Initial value of the Receiver property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="sentDate">Initial value of the SentDate property.</param>
        public static AlertNotification CreateAlertNotification(global::System.Int32 id, global::System.String sender, global::System.String receiver, global::System.String subject, global::System.String message, global::System.DateTime sentDate)
        {
            AlertNotification alertNotification = new AlertNotification();
            alertNotification.Id = id;
            alertNotification.Sender = sender;
            alertNotification.Receiver = receiver;
            alertNotification.Subject = subject;
            alertNotification.Message = message;
            alertNotification.SentDate = sentDate;
            return alertNotification;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sender
        {
            get
            {
                return _Sender;
            }
            set
            {
                OnSenderChanging(value);
                ReportPropertyChanging("Sender");
                _Sender = StructuralObject.SetValidValue(value, false, "Sender");
                ReportPropertyChanged("Sender");
                OnSenderChanged();
            }
        }
        private global::System.String _Sender;
        partial void OnSenderChanging(global::System.String value);
        partial void OnSenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Receiver
        {
            get
            {
                return _Receiver;
            }
            set
            {
                OnReceiverChanging(value);
                ReportPropertyChanging("Receiver");
                _Receiver = StructuralObject.SetValidValue(value, false, "Receiver");
                ReportPropertyChanged("Receiver");
                OnReceiverChanged();
            }
        }
        private global::System.String _Receiver;
        partial void OnReceiverChanging(global::System.String value);
        partial void OnReceiverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false, "Subject");
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false, "Message");
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SentDate
        {
            get
            {
                return _SentDate;
            }
            set
            {
                OnSentDateChanging(value);
                ReportPropertyChanging("SentDate");
                _SentDate = StructuralObject.SetValidValue(value, "SentDate");
                ReportPropertyChanged("SentDate");
                OnSentDateChanged();
            }
        }
        private global::System.DateTime _SentDate;
        partial void OnSentDateChanging(global::System.DateTime value);
        partial void OnSentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CC
        {
            get
            {
                return _CC;
            }
            set
            {
                OnCCChanging(value);
                ReportPropertyChanging("CC");
                _CC = StructuralObject.SetValidValue(value, true, "CC");
                ReportPropertyChanged("CC");
                OnCCChanged();
            }
        }
        private global::System.String _CC;
        partial void OnCCChanging(global::System.String value);
        partial void OnCCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BBC
        {
            get
            {
                return _BBC;
            }
            set
            {
                OnBBCChanging(value);
                ReportPropertyChanging("BBC");
                _BBC = StructuralObject.SetValidValue(value, true, "BBC");
                ReportPropertyChanged("BBC");
                OnBBCChanged();
            }
        }
        private global::System.String _BBC;
        partial void OnBBCChanging(global::System.String value);
        partial void OnBBCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attachments
        {
            get
            {
                return _Attachments;
            }
            set
            {
                OnAttachmentsChanging(value);
                ReportPropertyChanging("Attachments");
                _Attachments = StructuralObject.SetValidValue(value, true, "Attachments");
                ReportPropertyChanged("Attachments");
                OnAttachmentsChanged();
            }
        }
        private global::System.String _Attachments;
        partial void OnAttachmentsChanging(global::System.String value);
        partial void OnAttachmentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AlertType
        {
            get
            {
                return _AlertType;
            }
            set
            {
                OnAlertTypeChanging(value);
                ReportPropertyChanging("AlertType");
                _AlertType = StructuralObject.SetValidValue(value, "AlertType");
                ReportPropertyChanged("AlertType");
                OnAlertTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _AlertType;
        partial void OnAlertTypeChanging(Nullable<global::System.Int32> value);
        partial void OnAlertTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true, "ModifiedBy");
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value, "ModifiedDate");
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value, "EndDate");
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    }

    #endregion

}
